name: "Maven build"

on: 
  push # more make sense to be on merge even, simply for demo

jobs:
  static-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout #Q: this step name is defined by called action?
      - name: Setup JDK
        uses: actions/setup-java
        with: # supported version: 8/11/16/17, to be parameterize
          java-version: '11'
          cache: 'maven'

      - name: Sona scan
        run: echo "trigger sonaqube scan for code coverage"

      # and some others common useful steps ... 
      
      - name: Build with Maven
        run: echo "mvn clean install"
      







