name: "Maven build"

on: 
  push: # more make sense to be on merge even, simply for demo
  workflow_call: # todo: try to disable to confirm this is needed

jobs:
  static-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 #Q: this step name is defined by called action?
      - name: Setup JDK
        uses: actions/setup-java@v3
        with: # supported version: 8/11/16/17, to be parameterize
          java-version: '11'
          cache: 'maven'

      - name: Sona scan
        run: echo "trigger sonaqube scan for code coverage"

      # and some others common useful steps ... 

      - name: Build with Maven
        run: echo "mvn clean install"
      







